const enumArr = {
  sizeList: ["XXS", "XS", "S", "M", "L", "XL", "XXL", "XXXL", "VARIETY"],
  sexList: ["MALE", "FEMALE", "UNSEXED", "BREEDINGGROUP"],
  regionList: ["Malawi", "Tanganyika", "Victoria", "New World", "Other"],
  categoryList: ["PEACOCK", "HAP", "TANGANYIKA", "OTHER"],
  countryList: [
    "UnitedStates",
    "Canada",
    "Mexico",
    "UK",
    "Ireland",
    "Netherlands",
    "Germany",
    "Belgium",
    "France",
    "Thailand",
    "Vietnam",
    "Laos",
    "Cambodia",
    "Australia",
    "NewZealand",
    "Austria",
    "CzechRepublic",
    "China",
    "Poland",
    "Italy",
    "Greece",
    "Russia",
    "Japan",
    "Korea",
    "India",
    "Other",
  ],
  stateList: [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
  ],
};

const enumMap = {
  sizeMap: {
    XXS: 'up to 1"',
    XS: '1.25-2"',
    S: '2-2.5"',
    M: '2.75-3.25"',
    L: '3.5-4.5"',
    XL: '4.75-5.5"',
    XXL: '5.5-7"',
    XXXL: '7.5"+',
    VARIETY: "mixed",
  },
  sexMap: {
    MALE: "male",
    FEMALE: "female",
    UNSEXED: "unsexed",
    BREEDINGGROUP: "breeding group",
  },
  regionMap: {
    MALAWI: "Malawi",
    TANGANYIKA: "Tanganyika",
    VICTORIA: "Victoria",
    NEW_WORLD: "New World",
    OTHER: "Other",
  },
  categoryMap: {
    PEACOCK: "Peacock",
    HAP: "Hap",
    TANGANYIKA: "Tanganyikan",
    OTHER: "other",
  },
  countryMap: {
    UnitedStates: "United States",
    Canada: "Canada",
    Mexico: "Mexico",
    UK: "United Kingdom",
    Ireland: "Ireland",
    Netherlands: "Netherlands",
    Germany: "Germany",
    Belgium: "Belgium",
    France: "France",
    Thailand: "Thailand",
    Vietnam: "Vietnam",
    Laos: "Laos",
    Cambodia: "Cambodia",
    Australia: "Australia",
    NewZealand: "New Zealand",
    Austria: "Austria",
    CzechRepublic: "Czech Republic",
    China: "China",
    Poland: "Poland",
    Italy: "Italy",
    Greece: "Greece",
    Russia: "Russia",
    Japan: "Japan",
    Korea: "Korea",
    India: "India",
    Other: "other",
  },
  stateMap: {
    AL: "AL",
    AZ: "AZ",
    AR: "AR",
    AK: "AK",
    CA: "CA",
    CO: "CO",
    CT: "CT",
    DE: "DE",
    FL: "FL",
    GA: "GA",
    HI: "HI",
    ID: "ID",
    IL: "IL",
    IN: "IN",
    IA: "IA",
    KS: "KS",
    KY: "KY",
    LA: "LA",
    ME: "ME",
    MD: "MD",
    MA: "MA",
    MI: "MI",
    MN: "MN",
    MS: "MS",
    MO: "MO",
    MT: "MT",
    NE: "NE",
    NV: "NV",
    NH: "NH",
    NJ: "NJ",
    NM: "NM",
    NY: "NY",
    NC: "NC",
    ND: "ND",
    OH: "OH",
    OK: "OK",
    OR: "OR",
    PA: "PA",
    RI: "RI",
    SC: "SC",
    SD: "SD",
    TN: "TN",
    TX: "TX",
    UT: "UT",
    VT: "VY",
    VA: "VA",
    WA: "WA",
    WV: "WV",
    WI: "WI",
    WY: "WY",
  },
};

export { enumArr, enumMap };
