// 'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from '@/app/context/providers';
import Navbar from "@/app/components/NavBar";
const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
